import './globals.css';
import { Nunito } from 'next/font/google';
import AuthProvider from '@/Components/auth-provider/auth-provider';
import { Session } from 'next-auth';
const nuntito = Nunito({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface IRootLayoutProps {
  children: React.ReactNode;
  session: Session;
}

export default function RootLayout({ children, session }: IRootLayoutProps) {
  return (
    <html lang="en">
      <body className={nuntito.className + ' '} suppressHydrationWarning={true}>
        <AuthProvider session={session}>{children}</AuthProvider>
      </body>
    </html>
  );
}
